version: '3.8'

networks:
  xray_network:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
        - subnet: fd00:dead:beef::/48

services:
  xray_reality:
    image: damncrab/xray_docker_reality:latest
    container_name: xray_reality
    restart: always
    networks:
      - xray_network
    ports:
      - "443:443"
      - "[::]:443:443"
    environment:
      - EXTERNAL_PORT=443
    volumes:
      - ./config:/config
      - ./logs:/var/log/xray
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
